services:
  hueget:
    build:
      context: .
    container_name: hueget
    ports:
      - "3000:3000"
    environment:
      HUE_BRIDGE_IP: "192.168.0.101" # Replace with your Hue Bridge IP
      HUE_USERNAME: "yourPhilipsHueBridgeUsername" # Replace with your Hue username
    restart: unless-stopped